### ISSUE TITLE
Unable to clean directories on windows

### ISSUE THREAD

**Issue by cheahkhing** [gruntjs/grunt-contrib-clean#58]
The rules are being specified to clean all files and folders under tmp:
however, from time to time, it will failed to perform clean task and come out with error like this: (EPERM, operation not permitted '....tmp')
After some googling, it seems like this: http://stackoverflow.com/questions/23541343/grunt-clean-fail-unable-to-delete-tmp-file-eperm-operation-not-permitted

fixed the problem, but i think the package.json should be updated from here as well
Please verify if this is correct fix and include it in the package.json once and for all. :)

Thanks.

**Comment by sethlivingston** [comment]
Dont' know if this will help anyone else, but I was still encountering this problem even though I had the correct versions of everything. The problem was that another process (atom.exe in my case) had the folder locked, so nothing could delete it. When I closed the process, everything worked fine again.
